### ISSUE TITLE
Use `QueueDeclarePassive` instead of `QueueInspect`

### ISSUE THREAD

**Issue by gabo1208** [knative-extensions/eventing-rabbitmq#1052]
**Problem**
Use `QueueDeclarePassive` instead of `QueueInspect` to check for existing Queues, as the latter is going to be deprecated

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Contributors, Developers

**Exit Criteria**
Function change succeeded

**Additional context (optional)**
https://github.com/rabbitmq/amqp091-go/discussions/165#discussioncomment-4843420

**Comment by Iiqbal2000** [comment]
Hi @gabo1208, can I pick this up?

**Comment by gabo1208** [comment]
Of course! =)

**Comment by Iiqbal2000** [comment]
Hi @gabo1208, There are different parameters between `QueueInspect` and `QueueDeclarePassive`, are there any default values we can utilize for `QueueDeclarePassive`?
