### ISSUE TITLE
Health check not representative of state of dispatcher pod

### ISSUE THREAD

**Issue by lpfann** [knative-extensions/eventing-rabbitmq#1214]
**Describe the bug**
Even though the dispatcher pod is having connection issues, its health status is green.

 **Expected behavior**
The pod status should represent the true error state of its service.  This would help trigger alarm notifications or solve issues fixed by restarts.

 **To Reproduce**
Remove credentials used for dispatcher pod to connect to RabbitMQ cluster to trigger connection errors.
Dispatcher pod will show logs like this:
```
{"level":"error","ts":"2023-09-01T09:40:17.781Z","logger":"rabbitmq-dispatcher","caller":"rabbit/connections_handler.go:147","msg":"failed to create RabbitMQ connection, error: Exception (403) Reason: \"username or password not allowed\"","commit":"7031a4e-dirty","stacktrace":"knative.dev/eventing-rabbitmq/pkg/rabbit.(*RabbitMQConnectionHandler).createConnectionAndChannel\n\tknative.dev/eventing-rabbitmq/pkg/rabbit/connections_handler.go:147\nknative.dev/eventing-rabbitmq/pkg/rabbit.(*RabbitMQConnectionHandler).Setup\n\tknative.dev/eventing-rabbitmq/pkg/rabbit/connections_handler.go:118\nmain.main\n\tknative.dev/eventing-rabbitmq/cmd/dispatcher/main.go:108\nruntime.main\n\truntime/proc.go:250"}
```
Health status shows green. 

 **Knative release version**
v1.11.1

**Comment by gabo1208** [comment]
Next week should be released the new version that erros when the RabbitMQ Broker or Source can't connect to the RabbitMQ instance
