### ISSUE TITLE
RabbitMQ message order

### ISSUE THREAD

**Issue by gunpuz** [knative-extensions/eventing-rabbitmq#1347]
**Describe the bug**
Seems that order of messages are sometimes not in order they are submitted to queue

**Scheduler service writes after posting to RabbitMQ**
```
[14:36:54 INF] Task '39292ebc-1e70-4ccd-b988-2ed4ad501dc7' scheduled
[14:37:04 INF] Task '0ee03c07-4791-4100-9e9b-e45654d720b5' scheduled
```

**Worker received**
```
"Feb 7, 2024 @ 16:37:15.564","2024-02-07 14:37:15,564 INFO     [main:app:36] Received request json: {'task': '0ee03c07-4791-4100-9e9b-e45654d720b5'}","worker-00013-deployment-6dbc8fb464-pncgm"
"Feb 7, 2024 @ 16:38:56.855","2024-02-07 14:38:56,855 INFO     [main:app:36] Received request json: {'task': '39292ebc-1e70-4ccd-b988-2ed4ad501dc7'}","worker-00013-deployment-6dbc8fb464-n624f"
```

Waiting: 39292ebc-1e70-4ccd-b988-2ed4ad501dc7
Already received by worker, but it was submitted later: 0ee03c07-4791-4100-9e9b-e45654d720b5

 **Expected behavior**

Messages are consumed in FIFO order
https://www.rabbitmq.com/queues.html

 **To Reproduce**
Submitting many jobs?

 **Knative release version**
1.9.0

 **Additional context**
-

**Comment by gabo1208** [comment]
Hey @gunpuz what's your setup/topology?

and are you using the FIFO configuration? https://github.com/knative-extensions/eventing-rabbitmq/blob/main/samples/quick-setup/broker-files/400-trigger.yaml#L10

**Comment by gunpuz** [comment]
Hi, I am using parallelism of ~ `rabbitmq.eventing.knative.dev/parallelism: "100"`
Yes I guess it is logical, that FIFO queue is sequential in RabbitMQ and Knative RabbitMQ source would introduce some randomness. 
But is this normal, that job, that is enqueued 10 seconds later (in this example, maybe in other cases it could be more) gets processed as first?

If these are long running workers, that would mean that job is processed for example 1 / 5 / 10 minutes later than it supposed to.

**Comment by gabo1208** [comment]
Shouldn't be the case but could mean something else happened.
- Let's try to divide the problem, first thing, setting a parallelism of 1 should make sure you are processing it in a FIFO manner as per docs
- A bit more details in your case could help, could've happened that the Broker/Trigger or even the sink were cold starting and it took the whole system around 10 seconds to be stable, then it processed first the second message.

**Comment by gunpuz** [comment]
Yeah, I think that this "issue" (feature?) if we can call it that way is related to parallelism > 1. Sure, increasing parallelism as docs state does not proviede FIFO guarantees anymore, but I was wondering is there any room that we can maybe minimize this issue 😊. 10 seconds (as shown in example above) seems a lot of time where decisions about which message to send maybe could be decided.

About details, does this info help?:
- `RabbitMQ server` and `RabbitMQ source` was already up and running for a while, maybe few days..
- There were already some 10 - 20 other "jobs" / "tasks" that were processing from this single RabbitMQ source at that time when this issue was discovered

Don't know much about RabbitMQ source implementation, but does the RabbitMQ source parallelism means that every parallel "thread" reads the messages from RabbitMQ independently from other "threads"? If messages are not read at the single place, maybe thats what is causing this? 🤔

**Comment by gabo1208** [comment]
Yep sort of that what parallelism means.
With parallelism 1 there is just one thread reading messages and then waiting for the response to ack them in the rabbitmq queue
With more than 1 then there are many threads looking to read messages from the queue and then wait to ack each one of them. So any thread could be waiting for a response from your sink to ack the message while others could read and send the message meanwhile

**Comment by gunpuz** [comment]
Would it be possible to prefetch messages in single place and then distribute messages to "free" worker "threads" where these threads can wait for messages to be processed and then ask for new message?

**Comment by gabo1208** [comment]
I'm not 100% sure, but it sounds that this is not possible with this Knative Eventing integration. This is going to wait for messages that get to the Queue and poll them immediately. So if you are not limiting the messages that get to the Knative RabbitMQ broker, then there is not much to do regarding the source (you could be creative and maybe kill the pod of the source and then recreate it, but it's like a hacky workaround to me)

One other option is to "read" messages from your workers (or worker intermediary), so you consume the messages from that app and stop consuming whenever it's busy enough (or it cannot find free workers), this way the messages will wait in the RabbitMQ Queue and will not be pushed to consumers when there is none "consuming"
