### ISSUE TITLE
Add metadata to Dead lettered Messages

### ISSUE THREAD

**Issue by gabo1208** [knative-extensions/eventing-rabbitmq#833]
**Problem**
Messages that fail to be delivered are Dead lettered without any modification, leaving the system/user with no easy way to know why they ended up there. A knative recommendation for this is to add some extra fields in this case that adds that missing info:
https://knative.dev/docs/eventing/event-delivery/#configuring-channel-event-delivery

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Users

**Exit Criteria**
Deadlettered messages now have metadata on why they ended up in the DLQ
- [x] Implement DLQ metadata for the Broker https://github.com/knative-sandbox/eventing-rabbitmq/pull/1163
- [x] Implement DLQ metadata for the Source

**Comment by andrewwebber** [comment]
Is there any update on this other than it is scheduled for the "next" release?

**Comment by gabo1208** [comment]
Yes @andrewwebber We are finally getting this into Knative RabbitMQ!

We had some issues since is not well supported yet in RabbitMQ but we ended up implementing a solution here meanwhile!
